platform :ios, '7.0'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'AFNetworking', '~> 1.3.3'
pod 'Reachability', '~> 3.1.1'
pod 'Evernote-SDK-iOS', '~> 1.3.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'STTweetLabel', '~> 3.1.8'
pod 'SDWebImage', '~> 3.5.4'
pod 'YLGIFImage', '~> 0.1'
