platform :ios, '7.0'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'AFNetworking', '~> 1.3.3'
pod 'Reachability', '~> 3.1.1'
pod 'RESideMenu', '~> 3.2'
pod 'Evernote-SDK-iOS', '~> 1.3.0'
pod 'MBProgressHUD', '~> 0.8'